### PR TITLE
Always specify ${BUILD_DIR} as parameter to ${SETUP_SCRIPT}

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@darknighte I'm not sure if this is right but it seems that the calls to oe-init-build-env always require the build dir to be the first parameter.

In my case I was running something like:
```
bbsh -b pyro/build/beaglebone/ -l pyro/src/poky/
```

while this would work as expected, the way the initial invocation of ${SETUP_SCRIPT} was handled, I was getting a spurious build/ dir created in the directory where I invoked bbsh.

I suspect I'm missing something related to first build creation or something but so far I have not used bbsh to actually create my build directory.

Thoughts?

**Comment by darknighte** [comment]
@drewmoseley What error are you seeing? Do you have a sample output that shows the error?

**Comment by drewmoseley** [comment]
There are two scenarios.  One on creating the initial directory:

```
$ bbsh -b build/raspberrypi2 -l src/poky -i
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
/home/dmoseley/dmoseley/bbsh/bbsh: line 586: BUILD_DIR: parameter null or not set
```

That may actually be a second issue.  I generally use build/<blah> for my build dirs to keep them isolated from each other. It appears that this script has an issue with anything not in the current directory.  If I drop it to a single directory then it works.

(I suspect the dirname errors are a symptom of this)

**Comment by drewmoseley** [comment]
The initial issue I saw was when using this with an existing build dir.  I do this because I have an external script that runs oe-init-build-env, sets up layers and local.conf settings and such.

```
$ ls
total 8
4 build/  4 src/
$ ls build/
total 4
4 qemuarm/
$ ls build/qemuarm/
total 12
0 bitbake.lock  4 cache/  4 conf/  4 tmp/
$ bbsh -b build/qemuarm/ -l src/poky/
BITBAKE SHELL-(1):qemuarm$ exit
$ ls
total 8
4 build/  4 src/
$ ls build/
total 8
4 conf/  4 qemuarm/
```

Note the newly added build/conf dir because of the initial invocation of the SETUP_SCRIPT with no parameters.

**Comment by drewmoseley** [comment]
@darknighte I pushed a second commit to handle the case of a multi-part build directory name.  I think it may be a bit clearer now.  Let me know what you think.

**Comment by darknighte** [comment]
@drewmoseley I think we should split this into two PRs.  I agree with the expansion of the directories didn't account for multiple levels, but the other bug looks like an existing issue [here](https://github.com/MentorEmbedded/bbsh/issues/1).  I would like to look at them separately to get the fix for the former, while looking at the latter.

**Comment by drewmoseley** [comment]
OK.  Closing this.  I'll resubmit as separate PRs.

**Pull request closed without merging**
